// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtJcITl5pHN9Ykegp-Abl5kW633RWywIg',
    appId: '1:30794948921:web:dec0a4f8ef4e6ad7e388e8',
    messagingSenderId: '30794948921',
    projectId: 'umra-guide-8ba28',
    authDomain: 'umra-guide-8ba28.firebaseapp.com',
    storageBucket: 'umra-guide-8ba28.firebasestorage.app',
    measurementId: 'G-KWSFY3NP31',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAO4lkiEL-yHzhsZpjWzRLbCzJAx7X7yGA',
    appId: '1:30794948921:android:22fdf88f3bd87684e388e8',
    messagingSenderId: '30794948921',
    projectId: 'umra-guide-8ba28',
    storageBucket: 'umra-guide-8ba28.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6w_YIn0jN5O7HGxXV2mQ7oK11FcX0Pkk',
    appId: '1:30794948921:ios:791ae163a1a2858de388e8',
    messagingSenderId: '30794948921',
    projectId: 'umra-guide-8ba28',
    storageBucket: 'umra-guide-8ba28.firebasestorage.app',
    iosBundleId: 'saydulayev.wien-gmail.com.umra',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6w_YIn0jN5O7HGxXV2mQ7oK11FcX0Pkk',
    appId: '1:30794948921:ios:ae920ea814266791e388e8',
    messagingSenderId: '30794948921',
    projectId: 'umra-guide-8ba28',
    storageBucket: 'umra-guide-8ba28.firebasestorage.app',
    iosBundleId: 'com.example.umraFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtJcITl5pHN9Ykegp-Abl5kW633RWywIg',
    appId: '1:30794948921:web:f13181eab0ea522ee388e8',
    messagingSenderId: '30794948921',
    projectId: 'umra-guide-8ba28',
    authDomain: 'umra-guide-8ba28.firebaseapp.com',
    storageBucket: 'umra-guide-8ba28.firebasestorage.app',
    measurementId: 'G-J4ZR73W9YJ',
  );
}
